In [412]:
import pandas as pd

df = pd.read_csv(r'C:\Users\MS994\Downloads\fds\depression_dataset_raw.csv')


df['How do you usually cope with stress?'] = (
    df['How do you usually cope with stress?']
    .astype(str)
    .str.replace('â€™', "'", regex=False)
    .str.replace('â€œ', '"', regex=False)
    .str.replace('â€�', '"', regex=False)
)





# Clean column names
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r'[^\w]+', '_', regex=True)
)

In [414]:
# Remove duplicate rows
df = df.drop_duplicates()

# Drop completely empty rows
df = df.dropna(how='all')

In [415]:
print(df.isnull().sum())

timestamp                                             0
age_                                                  0
gender_                                               0
how_often_do_you_feel_stressed_                       0
how_often_do_you_feel_anxious_or_worried_             0
how_often_do_you_feel_sad_or_low_                     1
do_you_feel_overwhelmed_by_daily_tasks_               0
do_you_have_difficulty_concentrating_                 0
how_often_do_you_overthink_situations_                0
do_you_experience_mood_swings_                        1
how_many_hours_do_you_sleep_daily_                    0
how_often_do_you_feel_tired_or_low_on_energy_         1
do_you_feel_supported_by_people_around_you_           1
how_often_do_you_socialize_with_others_               0
how_do_you_usually_cope_with_stress_                  0
how_would_you_rate_your_overall_mental_well_being_    0
dtype: int64

In [416]:
df = df.rename(columns={
    'how_often_do_you_feel_stressed_': 'stress',
    'how_often_do_you_feel_anxious_or_worried_': 'anxiety',
    'how_often_do_you_feel_sad_or_low_': 'sadness',
    'do_you_feel_overwhelmed_by_daily_tasks_': 'overwhelmed',
    'do_you_have_difficulty_concentrating_': 'concentration',
    'how_often_do_you_overthink_situations_': 'overthinking',
    'do_you_experience_mood_swings_': 'mood_swings',
    'how_many_hours_do_you_sleep_daily_': 'sleep_raw',
    'how_often_do_you_feel_tired_or_low_on_energy_': 'tired',
    'do_you_feel_supported_by_people_around_you_': 'support',
    'how_often_do_you_socialize_with_others_': 'social',
    'how_do_you_usually_cope_with_stress_': 'coping',
    'how_would_you_rate_your_overall_mental_well_being_': 'wellbeing'
})

df = df.apply(lambda col: col.astype(str).str.strip().str.capitalize())

In [417]:
df['wellbeing'] = df['wellbeing'].astype(str).str.lower().str.strip()
wellbeing_map = {
    'very poor': 1,
    'poor': 2,
    'average': 3,
    'good': 4,
    'excellent': 5
}

df['wellbeing'] = df['wellbeing'].replace(wellbeing_map)

df['wellbeing'] = pd.to_numeric(df['wellbeing'], errors='coerce')

df['wellbeing'] = df['wellbeing'].fillna(df['wellbeing'].median())

df.head(10)

,timestamp,age_,gender_,stress,anxiety,sadness,overwhelmed,concentration,overthinking,mood_swings,sleep_raw,tired,support,social,coping,wellbeing
0,2026/03/24 7:37:41 pm gmt+5:30,21,Female,Always,Often,Often,Sometimes,Sometimes,Often,Yes,05-jun,Sometimes,Yes,Weekly,Music/entertainment,1
1,2026/03/24 7:41:03 pm gmt+5:30,21,Male,Sometimes,Sometimes,Often,No,Sometimes,Always,Sometimes,07-aug,Sometimes,Yes,Daily,Sleeping,4
2,2026/03/24 7:41:38 pm gmt+5:30,22,Female,Never,Sometimes,Sometimes,Sometimes,Never,Rarely,Yes,More than 8,Sometimes,Yes,Daily,Talking to someone,5
3,2026/03/24 7:47:09 pm gmt+5:30,21,Male,Always,Never,Always,Yes,Sometimes,Often,Yes,More than 8,Never,No,Weekly,Talking to someone,3
4,2026/03/24 7:48:26 pm gmt+5:30,22,Male,Often,Often,Often,No,Sometimes,Sometimes,No,05-jun,Sometimes,Yes,Daily,Music/entertainment,5
5,2026/03/24 7:57:47 pm gmt+5:30,19,Female,Sometimes,Sometimes,Always,Sometimes,Sometimes,Always,Yes,05-jun,Always,No,Daily,Sleeping,3
6,2026/03/24 8:01:24 pm gmt+5:30,20,Female,Always,Always,Often,Yes,Often,Always,Sometimes,05-jun,Always,No,Rarely,Avoiding problems,2
7,2026/03/24 8:01:35 pm gmt+5:30,21,Female,Always,Always,Always,Often,Often,Always,Often,Less than 5 hours,Always,No,Rarely,I don’t cope well,1
8,2026/03/24 8:08:25 pm gmt+5:30,18,Female,Often,Sometimes,Often,Sometimes,Always,Sometimes,Yes,05-jun,Sometimes,Yes,Daily,Music/entertainment,4
9,2026/03/24 8:19:19 pm gmt+5:30,20,Male,Sometimes,Sometimes,Sometimes,No,Sometimes,Sometimes,No,More than 8,Sometimes,Yes,Weekly,Music/entertainment,5

In [418]:
for col in ['stress','anxiety','sadness','overwhelmed',
            'concentration','overthinking','tired',
            'social','support','mood_swings','sleep_raw','coping']:
    
    print(col, "→", df[col].unique())
    print()

stress → ['Always' 'Sometimes' 'Never' 'Often']

anxiety → ['Often' 'Sometimes' 'Never' 'Always']

sadness → ['Often' 'Sometimes' 'Always' 'Nan' 'Never']

overwhelmed → ['Sometimes' 'No' 'Yes' 'Often']

concentration → ['Sometimes' 'Never' 'Often' 'Always']

overthinking → ['Often' 'Always' 'Rarely' 'Sometimes']

tired → ['Sometimes' 'Never' 'Always' 'Often' 'Nan']

social → ['Weekly' 'Daily' 'Rarely' 'Never']

support → ['Yes' 'No' 'Sometimes' 'Nan']

mood_swings → ['Yes' 'Sometimes' 'No' 'Often' 'Nan']

sleep_raw → ['05-jun' '07-aug' 'More than 8' 'Less than 5 hours' 'Less than 5']

coping → ['Music/entertainment' 'Sleeping' 'Talking to someone' 'Avoiding problems'
 'I don’t cope well' 'Other' 'Exercise']

In [419]:
import numpy as np
df.replace("Nan", np.nan, inplace=True)

In [420]:
df['overwhelmed'] = df['overwhelmed'].replace({
    'Yes': 'Often',
    'No': 'Never'
})

In [421]:
df['support'] = df['support'].replace({
    'Yes': 'Often',
    'No': 'Never'
})

In [422]:
df['mood_swings'] = df['mood_swings'].replace({
    'Yes': 'Often',
    'No': 'Never'
})

In [423]:
df['social'] = df['social'].replace({
    'Daily': 'Always',
    'Weekly': 'Often'
})

In [424]:
def clean_sleep(val):
    val = str(val).lower()

    if 'less' in val:
        return 'Less than 5'
    elif 'more' in val:
        return 'More than 8'
    else:
        return '5-7'

df['sleep'] = df['sleep_raw'].apply(clean_sleep)
df=df.drop('sleep_raw',axis=1)

In [425]:
df['coping'] = df['coping'].replace({
    'Music/entertainment': 'Healthy',
    'Talking to someone': 'Healthy',
    'Exercise': 'Healthy',
    'Sleeping': 'Neutral',
    'Avoiding problems': 'Avoidance',
    'Other': 'Neutral',
    'I don’t cope well': 'Avoidance'   # ← EXACT match
})

In [426]:
df.fillna(df.mode().iloc[0], inplace=True)

In [427]:
likert = {
    "Never": 0,
    "Rarely": 1,
    "Sometimes": 2,
    "Often": 3,
    "Always": 4
}

cols = ['stress','anxiety','sadness','overwhelmed',
        'concentration','overthinking','tired',
        'social','support','mood_swings']

for col in cols:
    df[col] = df[col].map(likert)

In [428]:
df['sleep'] = df['sleep'].map({
    'Less than 5': 0,
    '5-7': 1,
    'More than 8': 2
})

df['coping'] = df['coping'].map({
    'Healthy': 1,
    'Neutral': 2,
    'Avoidance': 3
})

In [429]:
df['emotional_score'] = df[['stress','anxiety','sadness']].mean(axis=1)

df['cognitive_score'] = df[['overthinking','concentration','overwhelmed']].mean(axis=1)

df['sleep_risk'] = 2 - df['sleep']
df['physical_score'] = (df['sleep_risk'] + df['tired']) / 2

df['social_score'] = (df['social'] + df['support']) / 2

df['behavioral_score'] = (df['mood_swings'] + df['coping']) / 2

In [430]:
df[['emotional_score','cognitive_score','physical_score',
    'social_score','behavioral_score']].head()

,emotional_score,cognitive_score,physical_score,social_score,behavioral_score
0,3.333333,2.333333,1.5,3.0,2.0
1,2.333333,2.000000,1.5,3.5,2.0
2,1.333333,1.000000,1.0,3.5,2.0
3,2.666667,2.666667,0.0,1.5,2.0
4,3.000000,1.333333,1.5,3.5,0.5

In [431]:
df['drs_raw'] = (
    df['emotional_score'] * 0.30 +
    df['cognitive_score'] * 0.25 +
    df['physical_score'] * 0.20 +
    df['behavioral_score'] * 0.10 -
    df['social_score'] * 0.15
)

In [432]:
#normalize
df['drs'] = (df['drs_raw'] / 4) * 100

In [433]:
def categorize(score):
    if score <= 33:
        return "Low"
    elif score <= 66:
        return "Moderate"
    else:
        return "High"

df['risk_level'] = df['drs'].apply(categorize)

In [434]:
df[['drs','risk_level']].head()

         drs risk_level
0  40.833333   Moderate
1  29.375000        Low
2  13.125000        Low
3  36.041667   Moderate
4  26.458333        Low

In [435]:
print(df['risk_level'].value_counts())

risk_level
Moderate    446
Low         213
High        147
Name: count, dtype: int64

In [436]:
print(df[['drs','emotional_score','cognitive_score']].corr())

                      drs  emotional_score  cognitive_score
drs              1.000000         0.837392         0.718781
emotional_score  0.837392         1.000000         0.405140
cognitive_score  0.718781         0.405140         1.000000

In [439]:
df.to_csv("C:/Users/MS994/Downloads/fds/depression_analysis_processed.csv", index=False)

In [437]:
df.columns = df.columns.str.strip().str.lower()

# Rename properly
df = df.rename(columns={
    'age_': 'age',
    'gender_': 'gender'
})

print(df.columns)

Index(['timestamp', 'age', 'gender', 'stress', 'anxiety', 'sadness',
       'overwhelmed', 'concentration', 'overthinking', 'mood_swings', 'tired',
       'support', 'social', 'coping', 'wellbeing', 'sleep', 'emotional_score',
       'cognitive_score', 'sleep_risk', 'physical_score', 'social_score',
       'behavioral_score', 'drs_raw', 'drs', 'risk_level'],
      dtype='object')

In [438]:
df = df[df['age'].astype(str).str.isnumeric()]
df['age'] = df['age'].astype(int)
df.head()

,timestamp,age,gender,stress,anxiety,sadness,overwhelmed,concentration,overthinking,mood_swings,...,sleep,emotional_score,cognitive_score,sleep_risk,physical_score,social_score,behavioral_score,drs_raw,drs,risk_level
0,2026/03/24 7:37:41 pm gmt+5:30,21,Female,4,3,3,2,2,3,3,...,1,3.333333,2.333333,1,1.5,3.0,2.0,1.633333,40.833333,Moderate
1,2026/03/24 7:41:03 pm gmt+5:30,21,Male,2,2,3,0,2,4,2,...,1,2.333333,2.000000,1,1.5,3.5,2.0,1.175000,29.375000,Low
2,2026/03/24 7:41:38 pm gmt+5:30,22,Female,0,2,2,2,0,1,3,...,2,1.333333,1.000000,0,1.0,3.5,2.0,0.525000,13.125000,Low
3,2026/03/24 7:47:09 pm gmt+5:30,21,Male,4,0,4,3,2,3,3,...,2,2.666667,2.666667,0,0.0,1.5,2.0,1.441667,36.041667,Moderate
4,2026/03/24 7:48:26 pm gmt+5:30,22,Male,3,3,3,0,2,2,0,...,1,3.000000,1.333333,1,1.5,3.5,0.5,1.058333,26.458333,Low

In [383]:
print(df.head())

                        timestamp  age  gender  stress  anxiety  sadness  \
0  2026/03/24 7:37:41 pm gmt+5:30   21  Female       4        3        3
1  2026/03/24 7:41:03 pm gmt+5:30   21    Male       2        2        3
2  2026/03/24 7:41:38 pm gmt+5:30   22  Female       0        2        2
3  2026/03/24 7:47:09 pm gmt+5:30   21    Male       4        0        4
4  2026/03/24 7:48:26 pm gmt+5:30   22    Male       3        3        3

   overwhelmed  concentration  overthinking  mood_swings  ...  sleep  \
0            2              2             3            3  ...      1
1            0              2             4            2  ...      1
2            2              0             1            3  ...      2
3            3              2             3            3  ...      2
4            0              2             2            0  ...      1

   emotional_score  cognitive_score  sleep_risk physical_score  social_score  \
0         3.333333         2.333333           1            1.5           3.0
1         2.333333         2.000000           1            1.5           3.5
2         1.333333         1.000000           0            1.0           3.5
3         2.666667         2.666667           0            0.0           1.5
4         3.000000         1.333333           1            1.5           3.5

   behavioral_score   drs_raw        drs  risk_level
0               2.0  1.633333  40.833333    Moderate
1               2.0  1.175000  29.375000         Low
2               2.0  0.525000  13.125000         Low
3               2.0  1.441667  36.041667    Moderate
4               0.5  1.058333  26.458333         Low

[5 rows x 25 columns]

In [440]:
# Coping Score Meaning:
# 0 → Very poor coping (Avoidance, "I don't cope well")
#     - No effective coping mechanism
#     - High vulnerability to depression

# 1 → Low coping (Neutral / passive coping like sleeping, other)
#     - Temporary relief but not problem-solving

# 2 → Moderate coping (e.g., Music/Entertainment)
#     - Distraction-based coping, somewhat helpful

# 3 → Healthy coping (e.g., Talking to someone, Exercise)
#     - Active and effective coping strategies
#     - Reduces depression risk

In [441]:
# Well-being Score Meaning:
# 1 → Very Poor (Severe distress, high depression risk)
# 2 → Poor (Low mental health)
# 3 → Average (Moderate mental state)
# 4 → Good (Stable mental health)
# 5 → Excellent (Very healthy mental state)

# Note:
# For depression scoring, this is usually inverted:
# depression_score = 6 - wellbeing

In [442]:
# Frequency Scale Meaning:
# 0 → Never (No symptoms)
# 1 → Rarely (Very low occurrence)
# 2 → Sometimes (Moderate occurrence)
# 3 → Often (Frequent symptoms)
# 4 → Always (Severe / constant symptoms)

In [443]:
# Sleep Score Meaning:
# 0 → Healthy sleep (7–8 hours)
# 1 → Slightly disturbed sleep
# 2 → Poor sleep
# 3 → Very poor sleep (<5 hours)

In [ ]:
# ================================
# DEPRESSION DATASET SCORING GUIDE
# ================================

# General Rule:
# Higher score → Higher depression severity
# Lower score → Better mental health

# -------------------------------
# CORE SYMPTOMS (0–4 scale)
# -------------------------------

# stress:
# 0 → Never stressed
# 1 → Rarely stressed
# 2 → Sometimes stressed
# 3 → Often stressed
# 4 → Always stressed

# anxiety:
# 0 → No anxiety
# 4 → Constant anxiety

# sadness:
# 0 → No sadness
# 4 → Persistent sadness

# overwhelmed:
# 0 → Never overwhelmed
# 4 → Always overwhelmed

# concentration:
# 0 → No difficulty
# 4 → Severe difficulty concentrating

# overthinking:
# 0 → No overthinking
# 4 → Constant overthinking

# mood_swings:
# 0 → Stable mood
# 4 → Frequent mood swings

# tired:
# 0 → Energetic
# 4 → Always tired / low energy

# -------------------------------
# SUPPORT & SOCIAL (0–4 scale)
# -------------------------------

# support:
# 0 → No support
# 4 → Strong support system
# NOTE: This should be inverted for scoring

# social:
# 0 → No social interaction
# 4 → Highly social
# NOTE: Invert for depression score

# -------------------------------
# COPING (0–3 scale)
# -------------------------------

# coping:
# 0 → Avoidance / "I don’t cope well"
# 1 → Passive coping (sleeping, other)
# 2 → Distraction coping (music, entertainment)
# 3 → Healthy coping (talking, exercise)
# NOTE: Invert for depression score

# -------------------------------
# WELL-BEING (1–5 scale)
# -------------------------------

# wellbeing:
# 1 → Very Poor mental health
# 2 → Poor
# 3 → Average
# 4 → Good
# 5 → Excellent
# NOTE: MUST be inverted → (6 - wellbeing)

# -------------------------------
# SLEEP (0–3 scale)
# -------------------------------

# sleep:
# 0 → Healthy sleep
# 1 → Slight disturbance
# 2 → Poor sleep
# 3 → Very poor sleep (<5 hrs)

# -------------------------------
# FINAL NOTE
# -------------------------------
# Positive factors (support, social, coping, wellbeing)
# should be inverted before calculating final depression score